apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: ahmed
spec:
  replicas: 2

  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app

    spec:
      containers:
        - name: java-app
          image: a7medsayed/depi-java-app:21

          ports:
            - containerPort: 8090

          envFrom:
            - configMapRef:
                name: java-app-config