apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: java-app
  namespace: argocd
spec:
  description: Project for Ahmed Java App

  sourceRepos:
    - "*"

  destinations:
    - namespace: ahmed
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
